apiVersion: v1
data:
  alert-rules.yaml: |-
    {{`
    groups:
    - name: cpu
      rules:
      # Alert is cpu usage is over 75% for >2 minutes.
      - alert: node_cpu_usage_high
        expr: (100 - (avg by (instance) (irate(node_cpu{name="node-exporter",mode="idle"}[5m])) * 100)) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"

    - name: instance-availability
      rules:
      # Alert if instance is down for >1 minutes.
      - alert: instance_down
        expr: up == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

    - name: disk-usage
      rules:
      - alert: node_low_root_disk
        expr: ((node_filesystem_size{mountpoint="/root-disk"} - node_filesystem_free{mountpoint="/root-disk"} ) / node_filesystem_size{mountpoint="/root-disk"} * 100) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: Low root disk space"
          description: "{{$labels.instance}}: Root disk usage is above 75% (current value is: {{ $value }})"
      - alert: node_low_data_disk
        expr: ((node_filesystem_size{mountpoint="/data-disk"} - node_filesystem_free{mountpoint="/data-disk"} ) / node_filesystem_size{mountpoint="/data-disk"} * 100) > 75
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: Low data disk space"
          description: "{{$labels.instance}}: Data disk usage is above 75% (current value is: {{ $value }})"

    - name: memory-usage
      rules:
      - alert: swap_usage_detected
        expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: Swap usage detected"
          description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"
      - alert: high_memory_usage
        expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 75
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: High memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"

    - name: portworx-volume-alerts
      rules:
      - alert: portworx_volume_usage_critical
        expr: 100*(px_volume_usage_bytes / px_volume_capacity_bytes) > 80
        for: 5m
        labels:
          severity: critical
          issue: "Portworx volume {{$labels.volumeid}} usage on {{$labels.instance}} is critical."
        annotations:
          summary: "Portworx volume usage is over 80% of capacity."
          description: "Portworx volume {{$labels.volumeid}} on {{$labels.instance}} is at {{$value}}% usage. Over 80% used for more than 5 minutes."
      - alert: portworx_volume_usage_high
        expr: 100*(px_volume_usage_bytes / px_volume_capacity_bytes) > 70
        for: 5m
        labels:
          severity: warning
          issue: "Portworx volume {{$labels.volumeid}} usage on {{$labels.instance}} is high."
        annotations:
          summary: "Portworx volume usage is over 70% of capacity."
          description: "Portworx volume {{$labels.volumeid}} on {{$labels.instance}} is at {{$value}}% usage. Over 70% used for more than 5 minutes."
      - alert: portworx_volume_approaching_full
        expr: (px_volume_usage_bytes / px_volume_capacity_bytes) > 0.7 and predict_linear(px_cluster_disk_available_bytes[1h], 14*86400) < 0
        for: 10m
        labels:
          severity: warning
          issue: "Portworx storage {{$labels.volumeid}} on {{$labels.instance}} is predicted to fill within 2 weeks."
        annotations:
          summary: "Portworx volume {{$labels.volumeid}} on {{$labels.instance}} is over 70% full and is predicted to fill within 2 weeks."
          description: "Disk volume {{$labels.volumeid}} on {{$labels.instance}} is over 70% full and has been predicted to fill within 2 weeks."

    - name: portworx-cluster-alerts
      rules:
      - alert: portworx_storage_usage_critical
        expr: 100*(1-px_cluster_disk_utilized_bytes / px_cluster_disk_available_bytes) < 20
        for: 5m
        labels:
          severity: "critical"
          issue: "Portworx storage {{$labels.volumeid}} usage on {{$labels.instance}} is critical."
        annotations:
          summary: "Portworx storage usage is over 80% capacity for more than 5 minutes."
          description: "Portworx storage {{$labels.volumeid}} on {{$labels.instance}} is at {{$value}}% usage. Over 80% used for more than 5 minutes."
      - alert: portworx_storage_usage_high
        expr: 100*(1-px_cluster_disk_utilized_bytes / px_cluster_disk_available_bytes) < 30
        for: 5m
        labels:
          severity: "warning"
          issue: "Portworx storage {{$labels.volumeid}} usage on {{$labels.instance}} is high."
        annotations:
          summary: "Portworx storage usage is over 70% capacity for more than 5 minutes."
          description: "Portworx storage {{$labels.volumeid}} on {{$labels.instance}} is at {{$value}}% usage. Over 70% used for more than 5 minutes."
      - alert: portworx_storage_approaching_full
        expr: (100*(1- (px_cluster_disk_utilized_bytes / px_cluster_disk_available_bytes))) < 30 and predict_linear(px_cluster_disk_available_bytes[1h], 14*86400) < 0
        for: 10m
        labels:
          severity: warning
          issue: "Portworx storage {{$labels.volumeid}} on {{$labels.instance}} is predicted to fill within 2 weeks."
        annotations:
          summary: "Portworx storage {{$labels.volumeid}} on {{$labels.instance}} is over 70% full and is predicted to fill within 2 weeks."
          description: "Portworx storage {{$labels.volumeid}} on {{$labels.instance}} is over 70% full and has been predicted to fill within 2 weeks."
      - alert: portworx_not_in_quorum
        expr: px_cluster_status_cluster_quorum > 1
        for: 5m
        labels:
          severity: "critical"
          issue: "Portworx Quorum Unhealthy."
        annotations:
          summary: "Portworx Quorum Unhealthy."
          description: "Portworx cluster Quorum Unhealthy for more than 5 minutes."
        `}}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-alerts
  namespace: monitoring
