server:
  global:
    scrape_interval: 30s
    scrape_timeout: 10s
    evaluation_interval: 30s
  extraConfigmapMounts:
    - name: prometheus-alerts
      mountPath: /etc/config/alerts
      configMap: prometheus-alerts
      readOnly: true

  schedulerName: stork

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 40Gi
    storageClass: px-db-rf2-sc

## Prometheus server ConfigMap entries
##
serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/config/rules/*.yaml
      - /etc/config/alerts/*.yaml

alertmanager:
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 2Gi
    storageClass: "px-db-rf2-sc"