{
 "title": "Portworx Cluster Dashboard Copy (no AM)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  {
   "title": "Portworx Cluster \"$Cluster\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Usage Meter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"})/sum(px_cluster_disk_total_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Avg. Cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(px_cluster_cpu_percent{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "# Nodes (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"})/sum(px_cluster_status_cluster_quorum{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "# Nodes online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_nodes_online{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=\"$Cluster\"})-min(px_cluster_status_storage_nodes_online{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Portworx Cluster \"$Cluster\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Storage Pool Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "px_pool_stats_pool_status", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_cpu_percent{cluster =~ \"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Memory utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_memory_utilized_percent{cluster =~ \"$Cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}