
persistence:
  enabled: true
  initChownData: true
  storageClassName: portworx-sc
  accessModes:
    - ReadWriteOnce
  size: 10Gi

schedulerName: stork

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

## Configure grafana dashboard providers
## ref: http://docs.grafana.org/administration/provisioning/#dashboards
##
## `path` must be /var/lib/grafana/dashboards/<provider_name>
##
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
  default:
    portworx-cluster-dashboard:
      file: dashboards/px-cluster-dashboard.json
    portworx-volume-dashboard:
      file: dashboards/px-volume-dashboard.json
    portworx-node-dashboard:
      file: dashboards/px-node-dashboard.json
    cp-kafka-dashboard:
      file: dashboards/cp-kafka-dashboard.json
    k8s-cluster-dashboard:
      file: dashboards/k8s-cluster-summary_rev1.json
    spark-performance-dashboard:
      file: dashboards/spark-performance-metrics_rev4.json
    elasticsearch-cluster-dashboard:
      file: dashboards/elasticsearch_rev4_2.json
    prometheus-stats:
      gnetId: 1
      revision: 1
      datasource: Prometheus

